CREATE TABLE IF NOT EXISTS tasks (
    id UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    title VARCHAR UNIQUE NOT NULL,
    active_at TIMESTAMP UNIQUE NOT NULL,
    status VARCHAR DEFAULT 'active'
);
